services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8080
    restart: on-failure
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    expose:
      - "8080"
    volumes:
      - $HOME:/root:ro
      - $HOME/ocp-instal-tool:/root/ocp-install-tool:rw
      - $HOME/.docker:/root/.docker:ro
      - /var/run/docker.sock:/var/run/docker.sock
    restart: on-failure
    stdin_open: true
    tty: true
