#EXAMPLE CONFIG FILE

sshPublicKeyFile = "/home/rbednar/.ssh/id_rsa.pub"

#Do not use other name than "config.json"
pullSecretFile = "/tmp/config.json"

clusterName = "mycluster-01"
userName = "rbednar"
outputDir = "./output"
