#EXAMPLE CONFIG FILE

###Customize values below####
clusterName = "mycluster-01"
userName = "rbednar" # username should match kerberos ID (needed by vmware cloud)
outputDir = "./output" # where script will save all output
cloudRegion = "eu-central-1"
#TODO: need vmware apiVIP and ingressVIP configured!

# Passwords
vmwarePassword = "GEtZpdTyJcxCOp)8*uHDo9o9d#o*yt0%"

####Do not change values below unless you're sure what you're doing#####
sshPublicKeyFile = "secrets/id_rsa.pub"
pullSecretFile = "secrets/config.json"
